### Create a new patient (patient-service publishes to patient-topic; analytics-service consumes and logs the event)
#POST http://localhost:8333/api/v1/patients
POST http://lb-40b4eb74.elb.localhost.localstack.cloud:8333/api/v1/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Albert Ebisuo CW5",
  "email": "cwebisuo@email.com",
  "address": "Pipkin Court 38",
  "dateOfBirth": "1978-09-21",
  "registeredDate": "2024-02-24"
}

###