### Login Request to retrieve a token
POST http://localhost:8333/auth/login
#POST http://localhost:8088/login
Content-Type: application/json

{
  "email": "testuser@test.com",
  "password": "password123"
}

> {% client.global.set("token", response.body.token) %}